### ISSUE TITLE
When running on Android, the following error log is output when switching between foreground and background.

### ISSUE THREAD

**Issue by AdamZay** [EmadBeltaje/flutter_getx_template#20]
***
FCM has been connected normally and can receive FCM messages, but some error logs will be output after the messages come
 The effect of awesome_notifications is not seen either

***

```
D/Android: [Awesome Notifications]( 8821): App is now Foreground (LifeCycleManager:94)
E/OpenGLRenderer( 8821): Unable to match the desired swap behavior.
E/qdgralloc( 8821): GetGpuPixelFormat: No map for format: 0x38
E/AdrenoUtils( 8821): <validate_memory_layout_input_parmas:1923>: Unknown Format 0
E/AdrenoUtils( 8821): <adreno_init_memory_layout:4634>: Memory Layout input parameter validation failed!
E/qdgralloc( 8821): GetGpuResourceSizeAndDimensions Graphics metadata init failed
E/Gralloc4( 8821): isSupported(1, 1, 56, 1, ...) failed with 1
E/GraphicBufferAllocator( 8821): Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 1
E/AHardwareBuffer( 8821): GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -1), handle=0x0
E/qdgralloc( 8821): GetGpuPixelFormat: No map for format: 0x38
E/AdrenoUtils( 8821): <validate_memory_layout_input_parmas:1923>: Unknown Format 0
E/AdrenoUtils( 8821): <adreno_init_memory_layout:4634>: Memory Layout input parameter validation failed!
E/qdgralloc( 8821): GetGpuResourceSizeAndDimensions Graphics metadata init failed
E/Gralloc4( 8821): isSupported(1, 1, 56, 1, ...) failed with 1
E/GraphicBufferAllocator( 8821): Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 1
E/AHardwareBuffer( 8821): GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -1), handle=0x0
D/Android: [Awesome Notifications]( 8821): App is now Background (LifeCycleManager:94)
```

**Comment by AdamZay** [comment]
The yaml file of the project has been upgraded. Will this be the reason?

```
name: game_client
version: 1.0.0+1
publish_to: 'none' 
description: "A new Flutter project."
environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.2 # for state management and context less stuff

  logger: ^2.5.0 # log events in clear way insted of (print)

  flutter_screenutil: ^5.9.3 # make app responsive

  dio: ^5.8.0+1 # for api requests
  http_mock_adapter: ^0.6.1 # mocking dio for testing
  pretty_dio_logger: ^1.4.0 # for dio api logging and debugging

  hive: ^2.2.3  # local database (SQFlite replacement)
  hive_flutter: ^1.1.0 # make it easy to use hive (no need for path provider)
  shared_preferences: ^2.5.3 # shared preferences persistence key value store

  firebase_core: ^3.14.0 # to initialize firebase services
  firebase_messaging: ^15.2.7 # fcm services
  awesome_notifications: ^0.10.1 # notifications services (will be used for fcm)

  flutter_launcher_icons: # change app icon
  change_app_package_name: # change package name
  rename_app: 1.6.3 # rename app

  flutter_svg:  # display svg vectors

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner:  # generate dart files
  hive_generator: # generate hive files
  pub_semver: ^2.2.0 # helper to generate hive models

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900



```
